config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    path('summernote/', include('django_summernote.urls')),
    path('__reload__/', include('django_browser_reload.urls')),
    path('admin/', admin.site.urls),

    path('', include('apps.main.urls')),
    path('account/', include('apps.account.urls')),
    path('student/', include('apps.dashboard.student.urls')),
    path('teacher/', include('apps.dashboard.teacher.urls')),
]


urlpatterns += [re_path(r'^i18n/', include('django.conf.urls.i18n'))]
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT})]
urlpatterns += [re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})]

core/models/accounts.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


# User model
class User(AbstractUser):
    USER_TYPE = (
        ('student', _('Студент')),
        ('teacher', _('Оқытушы')),
        ('admin', _('Администрация')),
    )

    USER_CLASS = (
        ('none', _('Топты таңдау')),
        ('8b', _('1-топ')),
        ('8v', _('2-топ')),
    )

    avatar = models.ImageField(_('Сурет'), upload_to='core/account/users/', blank=True, null=True)
    user_type = models.CharField(_('Қолданушы типі'), max_length=32, choices=USER_TYPE, default='student')
    user_class = models.CharField(_('Сыныбы'), max_length=32, choices=USER_CLASS, default='none')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = _('Қолданушы')
        verbose_name_plural = _('Қолданушылар')

ui/templates/layouts/account_layout.html
{% extends 'layouts/base_layout.html' %}
{% load static %}

{% block base_layout %}
<div class="grid md:flex items-start gap-8 py-6 px-4">
    <ul class="max-w-64 w-full hidden md:grid gap-1">
        <li>
            <a href="{% url 'account' %}" class="py-2 px-4 w-full block hover:bg-primary-100 rounded-lg {% if request.path == '/account/user/me/' %}bg-primary-600 hover:bg-primary-800 text-white{% endif %}">
                Аккаунт
            </a>
        </li>
        <li>
            <a href="{% url 'settings' %}" class="py-2 px-4 w-full block hover:bg-primary-100 rounded-lg {% if request.path == '/account/user/settings/' %}bg-primary-600 hover:bg-primary-800 text-white{% endif %}">
                Баптаулар
            </a>
        </li>
    </ul>

    <ul class="flex md:hidden w-full font-medium text-center">
        <li class="whitespace-nowrap">
            <a href="{% url 'account' %}" class="p-2 border-b-4 {% if request.path == '/account/user/me/' %}border-b-4 border-primary-600{% else %}border-transparent{% endif %}">
                Аккаунт
            </a>
        </li>
        <li>
            <a href="{% url 'settings' %}" class="p-2 border-b-4 {% if request.path == '/account/user/settings/' %}border-b-4 border-primary-600{% else %}border-transparent{% endif %}">
                Баптаулар
            </a>
        </li>
    </ul>

    <div class="flex-1">
        {% block account_layout %}
        {% endblock account_layout %}
    </div>
</div>
{% endblock base_layout %}

ui/templates/layouts/auth_layout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="w-full h-screen overflow-auto flex justify-center py-8 px-4 sm:px-0 sm:py-16 items-start bg-background">
    <div class="max-w-md w-full grid gap-4">
        <div class="relative">
            <a 
                href="{% url 'main' %}"
                class="w-52 mx-auto overflow-hidden block"    
            >
                <img src="{% static 'images/logo.svg' %}" alt="Logo" class="w-full">
            </a>
        </div>

        <div class="relative">
            {% block auth_layout %}
            {% endblock auth_layout %}
        </div>
    </div>
</div>
{% endblock %}

ui/templates/layouts/base_layout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<nav class="fixed top-0 z-40 w-full bg-white border-b border-border-200">
    <div class="h-14 px-3 lg:px-5 lg:pl-3">
        <div class="h-full flex items-center justify-between">
            <a 
                href="{% url 'student' %}" 
                class="flex items-center rounded-sm border border-transparent active:border active:border-dashed active:border-border-200"
            >
                <img src="{% static 'images/logo.svg' %}" class="h-6" alt="Biomedia Logo" />
            </a>

            <div class="flex items-center">
                {% if user.user_type == 'teacher' %}
                    <a href="/admin/"
                        class="flex transition-all text-white bg-primary-600 hover:bg-primary-800 focus:ring-3 focus:ring-primary-300 font-medium rounded-lg px-5 py-2.5">
                        Администрация
                    </a>
                {% endif %}
                <div class="flex items-center ms-3">
                    <button 
                        type="button"
                        class="flex text-sm rounded-full focus:ring-4 focus:ring-secondary-300"
                        aria-expanded="false" data-dropdown-toggle="dropdown-user"
                    >
                        <span class="sr-only">Open user menu</span>
                        {% if user.avatar %}
                            <img 
                                class="w-8 h-8 rounded-full"
                                src="{{ user.avatar.url }}" alt="user photo"
                            >
                        {% else %}
                            <div 
                                class="w-8 h-8 rounded-full bg-secondary-100 flex items-center justify-center text-foreground"
                            >
                                {{ user.first_name|first|upper }}{{ user.last_name|first|upper }}
                            </div>
                        {% endif %}
                    </button>

                    <div 
                        class="z-50 hidden my-4 list-none bg-white divide-y divide-secondary-100 rounded-sm shadow-sm"
                        id="dropdown-user"
                    >
                        <div class="px-4 py-3" role="none">
                            <h1 class="font-semibold text-base" role="none">
                                {{ user.first_name }} {{ user.last_name }}
                            </h1>
                            <p class="font-medium truncate text-blue-600 mb-1" role="none">
                                {{ user.email }}
                            </p>
                        </div>
                        <ul class="py-1" role="none">
                            <li>
                                <a href="{% url 'account' %}"
                                    class="block px-4 py-2 font-medium hover:bg-secondary-100"
                                    role="menuitem">Аккаунт</a>
                            </li>
                            <li>
                                <a href="#"
                                    class="block px-4 py-2 font-medium hover:bg-secondary-100"
                                    role="menuitem">Баптаулар</a>
                            </li>
                            <li>
                                <form action="{% url 'logout' %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="w-full cursor-pointer text-left block px-4 py-2 font-medium hover:bg-secondary-100">Шығу</button>
                                </form>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>

<div class="mt-14">
    {% block base_layout %}
    {% endblock base_layout %}
</div>
{% endblock content %}

ui/templates/layouts/lesson_layout.html
{% extends 'layouts/base_layout.html' %}
{% load static %}
{% load filters %}


{% block base_layout %}
<div class="grid lg:flex items-start p-8 gap-8">
    <div class="flex-1">
        {% block lesson_layout %}
        {% endblock lesson_layout %}
    </div>

    <div 
        id="accordion-collapse" 
        data-accordion="collapse" 
        data-active-classes="text-foreground"
        data-inactive-classes="text-muted"
        class="w-full lg:max-w-md border border-border-200 rounded-xl overflow-hidden"
    >
        {% for uc in user_chapters %}
            <h2 id="accordion-collapse-heading-{{ uc.id }}">
                <button 
                    type="button"
                    class="flex items-center gap-2 justify-between w-full p-4 font-semibold bg-white border-b border-border-200"
                    data-accordion-target="#accordion-collapse-body-{{ uc.id }}" 
                    aria-expanded="{% if uc.id == active_chapter_id %}true{% else %}false{% endif %}"
                    aria-controls="accordion-collapse-body-{{ uc.id }}"
                >
                    <div class="flex w-full items-center justify-between gap-4">
                        <div class="flex-1 flex gap-2 items-center">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                stroke-width="1" stroke-linecap="round" stroke-linejoin="round"
                                class="lucide lucide-folder-open-icon lucide-folder-open">
                                <path
                                    d="m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2" />
                            </svg>
                            <h1 class="text-left line-clamp-1">{{ uc.chapter.name }}</h1>
                        </div>

                        <div class="flex items-center gap-2">
                            {% if uc.is_completed %}
                                <div class="flex gap-1 items-center">
                                    <svg class="w-5 h-5 text-amber-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24"
                                        height="24" fill="currentColor" viewBox="0 0 24 24">
                                        <path
                                            d="M13.849 4.22c-.684-1.626-3.014-1.626-3.698 0L8.397 8.387l-4.552.361c-1.775.14-2.495 2.331-1.142 3.477l3.468 2.937-1.06 4.392c-.413 1.713 1.472 3.067 2.992 2.149L12 19.35l3.897 2.354c1.52.918 3.405-.436 2.992-2.15l-1.06-4.39 3.468-2.938c1.353-1.146.633-3.336-1.142-3.477l-4.552-.36-1.754-4.17Z" />
                                    </svg>
                                    <span>{{ uc.rating }}</span>
                                </div>
                            {% endif %}

                            {% if uc.percentage %}
                                <div class="w-24 bg-secondary-200 rounded-full overflow-hidden">
                                    <div 
                                        class="bg-primary-600 text-xs font-medium text-blue-100 text-center p-0.5 leading-none rounded-full" 
                                        style="width: {{ uc.percentage|floatformat:0 }}%"
                                    >{{ uc.percentage|floatformat:0 }}%</div>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                        stroke-width="1" stroke-linecap="round" stroke-linejoin="round"
                        data-accordion-icon
                        class="lucide lucide-chevron-up-icon lucide-chevron-up rotate-180 shrink-0">
                        <path d="m18 15-6-6-6 6" />
                    </svg>
                </button>
            </h2>
            <div
                id="accordion-collapse-body-{{ uc.id }}" 
                class="{% if uc.id == active_chapter_id %}block{% else %}hidden{% endif %}" 
                aria-labelledby="accordion-collapse-heading-{{ uc.id }}"
            >
                <div class="grid gap-2 p-4 bg-secondary-100">
                    {% with user_lessons_by_chapter|dict_get:uc.chapter.id as chapter_user_lessons %}
                        {% for ul in chapter_user_lessons %}
                            {% if ul.status == 'in-progress' or ul.status == 'finished' %}
                                {% url 'user_lesson' user_subject.id uc.id ul.id as lesson_url %}
                                <a
                                    href="{{ lesson_url }}"
                                    class="flex items-center gap-2 justify-between border border-secondary-200 rounded-lg p-4 {% if request.path == lesson_url %}bg-primary-600 text-white{% else %}bg-white{% endif %}"
                                >
                                    <div class="flex items-start gap-4">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                            stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"
                                            class="lucide lucide-presentation-icon lucide-presentation">
                                            <path d="M2 3h20" />
                                            <path d="M21 3v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V3" />
                                            <path d="m7 21 5-5 5 5" />
                                        </svg>

                                        <div class="grid flex-1">
                                            <h1 class="font-medium line-clamp-1">{{ uc.chapter.order }}.{{ forloop.counter }}-сабақ: {{ ul.lesson.title }}</h1>
                                        </div>
                                    </div>

                                    <div class="flex gap-1 items-center">
                                        <svg class="w-5 h-5 text-amber-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24"
                                            height="24" fill="currentColor" viewBox="0 0 24 24">
                                            <path
                                                d="M13.849 4.22c-.684-1.626-3.014-1.626-3.698 0L8.397 8.387l-4.552.361c-1.775.14-2.495 2.331-1.142 3.477l3.468 2.937-1.06 4.392c-.413 1.713 1.472 3.067 2.992 2.149L12 19.35l3.897 2.354c1.52.918 3.405-.436 2.992-2.15l-1.06-4.39 3.468-2.938c1.353-1.146.633-3.336-1.142-3.477l-4.552-.36-1.754-4.17Z" />
                                        </svg>
                                        <span>{{ ul.rating }}</span>
                                    </div>
                                </a>
                            {% else %}
                                <div
                                    class="flex gap-2 items-center justify-between border border-secondary-200 rounded-lg p-4 bg-white"
                                >
                                    <div class="flex items-start gap-2">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                            stroke-width="1" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-lock-icon lucide-lock">
                                            <rect width="18" height="11" x="3" y="11" rx="2" ry="2" />
                                            <path d="M7 11V7a5 5 0 0 1 10 0v4" />
                                        </svg>

                                        <div class="grid flex-1">
                                            <h1 class="font-medium line-clamp-1">{{ ul.lesson.title }}</h1>
                                        </div>
                                    </div>

                                     <div class="flex gap-1 items-center">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                            stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-clock-icon lucide-clock">
                                            <path d="M12 6v6l4 2" />
                                            <circle cx="12" cy="12" r="10" />
                                        </svg>
                                        <span>{{ ul.total_duration }}:00</span>
                                    </div>
                                </div>
                            {% endif %}
                        {% empty %}
                            <div class="flex gap-2 justify-center text-center text-muted p-4">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                    stroke-width="1" stroke-linecap="round" stroke-linejoin="round"
                                    class="lucide lucide-presentation-icon lucide-presentation">
                                    <path d="M2 3h20" />
                                    <path d="M21 3v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V3" />
                                    <path d="m7 21 5-5 5 5" />
                                </svg>
                                <span>Бөлім сабақтары қосылмаған</span>
                            </div>
                        {% endfor %}
                    {% endwith %}
                </div>
            </div>
        {% empty %}
            <div class="flex gap-2 justify-center text-center text-muted p-4">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                    stroke-width="1" stroke-linecap="round" stroke-linejoin="round"
                    class="lucide lucide-folder-open-icon lucide-folder-open">
                    <path
                        d="m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2" />
                </svg>
                <span>Пәннің бөлімдері қосылмаған</span>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock base_layout %}

ui/templates/layouts/teacher_layout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<nav class="fixed top-0 z-50 w-full bg-white border-b border-neutral-200">
    <div class="h-14 px-3 lg:px-5 lg:pl-3">
        <div class="h-full flex items-center justify-between">
            <div class="flex items-center gap-2 justify-start rtl:justify-end">
                <button 
                    data-drawer-target="logo-sidebar" 
                    data-drawer-toggle="logo-sidebar" 
                    aria-controls="logo-sidebar"
                    type="button"
                    class="inline-flex items-center p-2 rounded-lg sm:hidden hover:bg-neutral-100 focus:outline-none focus:ring-2 focus:ring-neutral-200"
                >
                    <span class="sr-only">Open sidebar</span>
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                        stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"
                        class="lucide lucide-align-left-icon lucide-align-left">
                        <path d="M15 12H3" />
                        <path d="M17 18H3" />
                        <path d="M21 6H3" />
                    </svg>
                </button>
                <a 
                    href="{% url 'home' %}" 
                    class="flex items-center rounded-sm border border-transparent active:border active:border-dashed active:border-neutral-200"
                >
                    <img src="{% static 'images/logo.svg' %}" class="h-6" alt="Biomedia Logo" />
                </a>
            </div>

            <div class="flex items-center">
                <div class="flex items-center ms-3">
                    <div>
                        <button 
                            type="button"
                            class="flex text-sm rounded-full focus:ring-4 focus:ring-neutral-300"
                            aria-expanded="false" data-dropdown-toggle="dropdown-user"
                        >
                            <span class="sr-only">Open user menu</span>
                            {% if user.avatar %}
                                <img 
                                    class="w-8 h-8 rounded-full"
                                    src="{{ user.avatar.url }}" alt="user photo"
                                >
                            {% else %}
                                <img 
                                    class="w-8 h-8 rounded-full"
                                    src="{% static 'images/user-avatar.jpg' %}" alt="user photo"
                                >
                            {% endif %}
                        </button>
                    </div>
                    <div 
                        class="z-50 hidden my-4 list-none bg-white divide-y divide-neutral-100 rounded-sm shadow-sm"
                        id="dropdown-user"
                    >
                        <div class="px-4 py-3" role="none">
                            <h1 class="font-semibold text-base" role="none">
                                {% if user.first_name and user.last_name %}
                                    {{ user.first_name }} {{ user.last_name }}
                                {% else %}
                                    {{ user.username }}
                                {% endif %}
                            </h1>
                            <p class="font-medium truncate text-blue-600 mb-1" role="none">
                                {{ user.email }}
                            </p>
                            <span class="bg-green-100 text-green-800 text-xs font-semibold mt-2 me-2 px-2.5 py-0.5 rounded-sm">
                                {{ user.get_user_type_display }}
                            </span>
                        </div>
                        <ul class="py-1" role="none">
                            <li>
                                <a href="{% url 'account_view' %}"
                                    class="block px-4 py-2 text-neutral-700 hover:bg-neutral-100"
                                    role="menuitem">Аккаунт</a>
                            </li>
                            <li>
                                <a href="#"
                                    class="block px-4 py-2 text-neutral-700 hover:bg-neutral-100"
                                    role="menuitem">Баптаулар</a>
                            </li>
                            <li>
                                <form action="{% url 'logout_view' %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="w-full cursor-pointer text-left block px-4 py-2 text-neutral-700 hover:bg-neutral-100">Шығу</button>
                                </form>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>

<aside 
    id="logo-sidebar"
    class="fixed top-0 left-0 z-40 w-64 h-screen pt-20 transition-transform -translate-x-full bg-white border-r border-neutral-200 sm:translate-x-0"
    aria-label="Sidebar"
>
    <div class="h-full px-3 pb-4 overflow-y-auto bg-white">
        <ul class="space-y-1 font-medium">
            <li>
                <a 
                    href="{% url 'home' %}"
                    class="flex items-center p-2 rounded-lg group {% if request.path == '/' %}bg-green-600 text-white hover:bg-green-600{% else %}hover:bg-neutral-100 {% endif %}">
                    <svg class="w-5 h-5 transition duration-75 {% if request.path == '/' %}text-white group-hover:text-white{% else %}group-hover:text-green-600{% endif %}"
                        aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 21">
                        <path
                            d="M16.975 11H10V4.025a1 1 0 0 0-1.066-.998 8.5 8.5 0 1 0 9.039 9.039.999.999 0 0 0-1-1.066h.002Z" />
                        <path
                            d="M12.5 0c-.157 0-.311.01-.565.027A1 1 0 0 0 11 1.02V10h8.975a1 1 0 0 0 1-.935c.013-.188.028-.374.028-.565A8.51 8.51 0 0 0 12.5 0Z" />
                    </svg>
                    <span class="ms-3">Басқару панелі</span>
                </a>
            </li>
            <li>
                <a 
                    href="{% url 'subjects' %}"
                    class="flex items-center p-2 rounded-lg group {% if request.path == '/subjects/' %}bg-green-600 text-white hover:bg-green-600{% else %}hover:bg-neutral-100{% endif %}"
                >
                    <svg class="shrink-0 w-5 h-5 transition duration-75 {% if request.path == '/subjects/' %}text-white group-hover:text-white{% else %}group-hover:text-green-600{% endif %}"
                        aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 18">
                        <path d="M6.143 0H1.857A1.857 1.857 0 0 0 0 1.857v4.286C0 7.169.831 8 1.857 8h4.286A1.857 1.857 0 0 0 8 6.143V1.857A1.857 1.857 0 0 0 6.143 0Zm10 0h-4.286A1.857 1.857 0 0 0 10 1.857v4.286C10 7.169 10.831 8 11.857 8h4.286A1.857 1.857 0 0 0 18 6.143V1.857A1.857 1.857 0 0 0 16.143 0Zm-10 10H1.857A1.857 1.857 0 0 0 0 11.857v4.286C0 17.169.831 18 1.857 18h4.286A1.857 1.857 0 0 0 8 16.143v-4.286A1.857 1.857 0 0 0 6.143 10Zm10 0h-4.286A1.857 1.857 0 0 0 10 11.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 18 16.143v-4.286A1.857 1.857 0 0 0 16.143 10Z" />
                    </svg>
                    <span class="flex-1 ms-3 whitespace-nowrap">Пәндер</span>
                </a>
            </li>

            <li>
                <a 
                    href="{% url 'subjects' %}"
                    class="flex items-center p-2 rounded-lg group {% if request.path == '/subjects/' %}bg-green-600 text-white hover:bg-green-600{% else %}hover:bg-neutral-100{% endif %}"
                >
                    <svg class="shrink-0 w-5 h-5 transition duration-75 {% if request.path == '/subjects/' %}text-white group-hover:text-white{% else %}group-hover:text-green-600{% endif %}"
                        aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 18">
                        <path d="M6.143 0H1.857A1.857 1.857 0 0 0 0 1.857v4.286C0 7.169.831 8 1.857 8h4.286A1.857 1.857 0 0 0 8 6.143V1.857A1.857 1.857 0 0 0 6.143 0Zm10 0h-4.286A1.857 1.857 0 0 0 10 1.857v4.286C10 7.169 10.831 8 11.857 8h4.286A1.857 1.857 0 0 0 18 6.143V1.857A1.857 1.857 0 0 0 16.143 0Zm-10 10H1.857A1.857 1.857 0 0 0 0 11.857v4.286C0 17.169.831 18 1.857 18h4.286A1.857 1.857 0 0 0 8 16.143v-4.286A1.857 1.857 0 0 0 6.143 10Zm10 0h-4.286A1.857 1.857 0 0 0 10 11.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 18 16.143v-4.286A1.857 1.857 0 0 0 16.143 10Z" />
                    </svg>
                    <span class="flex-1 ms-3 whitespace-nowrap">Топтар</span>
                </a>
            </li>

            <li>
                <a 
                    href="{% url 'subjects' %}"
                    class="flex items-center p-2 rounded-lg group {% if request.path == '/subjects/' %}bg-green-600 text-white hover:bg-green-600{% else %}hover:bg-neutral-100{% endif %}"
                >
                    <svg class="shrink-0 w-5 h-5 transition duration-75 {% if request.path == '/subjects/' %}text-white group-hover:text-white{% else %}group-hover:text-green-600{% endif %}"
                        aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 18">
                        <path d="M6.143 0H1.857A1.857 1.857 0 0 0 0 1.857v4.286C0 7.169.831 8 1.857 8h4.286A1.857 1.857 0 0 0 8 6.143V1.857A1.857 1.857 0 0 0 6.143 0Zm10 0h-4.286A1.857 1.857 0 0 0 10 1.857v4.286C10 7.169 10.831 8 11.857 8h4.286A1.857 1.857 0 0 0 18 6.143V1.857A1.857 1.857 0 0 0 16.143 0Zm-10 10H1.857A1.857 1.857 0 0 0 0 11.857v4.286C0 17.169.831 18 1.857 18h4.286A1.857 1.857 0 0 0 8 16.143v-4.286A1.857 1.857 0 0 0 6.143 10Zm10 0h-4.286A1.857 1.857 0 0 0 10 11.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 18 16.143v-4.286A1.857 1.857 0 0 0 16.143 10Z" />
                    </svg>
                    <span class="flex-1 ms-3 whitespace-nowrap">Білім алушылар</span>
                </a>
            </li>

            <li>
                <a 
                    href="{% url 'subjects' %}"
                    class="flex items-center p-2 rounded-lg group {% if request.path == '/subjects/' %}bg-green-600 text-white hover:bg-green-600{% else %}hover:bg-neutral-100{% endif %}"
                >
                    <svg class="shrink-0 w-5 h-5 transition duration-75 {% if request.path == '/subjects/' %}text-white group-hover:text-white{% else %}group-hover:text-green-600{% endif %}"
                        aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 18">
                        <path d="M6.143 0H1.857A1.857 1.857 0 0 0 0 1.857v4.286C0 7.169.831 8 1.857 8h4.286A1.857 1.857 0 0 0 8 6.143V1.857A1.857 1.857 0 0 0 6.143 0Zm10 0h-4.286A1.857 1.857 0 0 0 10 1.857v4.286C10 7.169 10.831 8 11.857 8h4.286A1.857 1.857 0 0 0 18 6.143V1.857A1.857 1.857 0 0 0 16.143 0Zm-10 10H1.857A1.857 1.857 0 0 0 0 11.857v4.286C0 17.169.831 18 1.857 18h4.286A1.857 1.857 0 0 0 8 16.143v-4.286A1.857 1.857 0 0 0 6.143 10Zm10 0h-4.286A1.857 1.857 0 0 0 10 11.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 18 16.143v-4.286A1.857 1.857 0 0 0 16.143 10Z" />
                    </svg>
                    <span class="flex-1 ms-3 whitespace-nowrap">Барлық пәндер</span>
                </a>
            </li>
        </ul>
    </div>
</aside>

<div class="sm:ml-64 mt-14">
    {% block instructor_layout %}
    {% endblock instructor_layout %}
</div>
{% endblock content %}